# app/utils/styles.py

CATEGORIES = [
    "Cinematic",
    "Fantasy",
    "Wedding",
    "Vintage",
    "Anime",
    "Luxury",
    "Travel",
    "Seasonal",
    "Cultural",
    "Artistic"
]

STYLE_PRESETS = [
    # ==========================================
    # CINEMATIC CATEGORY (8 Presets)
    # ==========================================
    {
        "id": "cinematic",
        "name": "Romantic Cinematic",
        "category": "Cinematic",
        "description": "Warm film tones with anamorphic aspect and soft cinematic lighting.",
        "use_cases": "Classic filmic looks, couples standing in streetlights or sunlit outdoor scenes.",
        "visual_treatment": "Anamorphic widescreen letterbox, film grain, gentle vignette, warm tones.",
        "thumbnail": "style_cinematic.jpg",
        "bg_gradient": ((10, 10, 8), (40, 36, 25)),
        "face_tint": (1.05, 1.0, 0.9),
        "brightness": 0.9,
        "contrast": 1.0,
        "saturation": 0.95,
        "special_effect": None,
        "overlay": "film_grain",
        "frame": "Cinematic Letterbox",
        "overlay_text": None,
        "overlay_subtext": None
    },
    {
        "id": "hollywood_romance",
        "name": "Hollywood Romance",
        "category": "Cinematic",
        "description": "High-contrast glamorous lighting reminiscent of silver screen romances.",
        "use_cases": "Formal attire, premium portraits, dramatic candlelit settings.",
        "visual_treatment": "Golden face-tints, rich shadows, medium film grain, slight halo glow.",
        "thumbnail": "style_hollywood_romance.jpg",
        "bg_gradient": ((15, 12, 10), (55, 45, 30)),
        "face_tint": (1.1, 1.0, 0.85),
        "brightness": 0.95,
        "contrast": 1.15,
        "saturation": 1.05,
        "special_effect": None,
        "overlay": "vignette",
        "frame": None,
        "overlay_text": "HOLLYWOOD LOVE",
        "overlay_subtext": "A CLASSIC TALE"
    },
    {
        "id": "netflix_drama",
        "name": "Netflix Drama",
        "category": "Cinematic",
        "description": "Modern streaming show color palette with cool shadows and warm highlights.",
        "use_cases": "Moody urban streets, casual modern couples, indie aesthetic.",
        "visual_treatment": "Teal-and-orange color grade, shallow depth of field, low-contrast shadows.",
        "thumbnail": "style_netflix_drama.jpg",
        "bg_gradient": ((8, 12, 15), (28, 48, 55)),
        "face_tint": (1.0, 1.02, 0.98),
        "brightness": 0.92,
        "contrast": 0.95,
        "saturation": 0.95,
        "special_effect": None,
        "overlay": "film_grain",
        "frame": None,
        "overlay_text": "ORIGINAL SERIES",
        "overlay_subtext": "LOVE IN SHADOWS"
    },
    {
        "id": "action_movie",
        "name": "Action Movie Couple",
        "category": "Cinematic",
        "description": "High energy blockbusters look with dramatic blue/orange dynamic contrast.",
        "use_cases": "Epic backgrounds, windy hillsides, dynamic action-adventure feel.",
        "visual_treatment": "High clarity, intense saturation, vignette, lens flares, cool cyan tint.",
        "thumbnail": "style_action_movie.jpg",
        "bg_gradient": ((5, 10, 15), (20, 45, 65)),
        "face_tint": (1.05, 0.95, 1.1),
        "brightness": 1.05,
        "contrast": 1.25,
        "saturation": 1.2,
        "special_effect": None,
        "overlay": "light_leak",
        "frame": None,
        "overlay_text": "THE RECKONING",
        "overlay_subtext": "TOGETHER WE STAND"
    },
    {
        "id": "paris_love_film",
        "name": "Paris Love Story",
        "category": "Cinematic",
        "description": "Romantic European arthouse movie style with soft pastel tones.",
        "use_cases": "Scenic landmarks, café dates, vintage European outfits.",
        "visual_treatment": "Desaturated tones, soft pastel highlights, light film grain, low contrast.",
        "thumbnail": "style_paris_love_film.jpg",
        "bg_gradient": ((40, 38, 40), (120, 110, 115)),
        "face_tint": (1.02, 1.0, 1.02),
        "brightness": 1.0,
        "contrast": 0.85,
        "saturation": 0.8,
        "special_effect": None,
        "overlay": "film_grain",
        "frame": None,
        "overlay_text": "AMOUR À PARIS",
        "overlay_subtext": "UN FILM DE L'AMOUR"
    },
    {
        "id": "sunset_beach_film",
        "name": "Sunset Beach Film",
        "category": "Cinematic",
        "description": "Retro California beach aesthetic with golden backlighting and warm grain.",
        "use_cases": "Beach walks, summer outfits, casual outdoor couples.",
        "visual_treatment": "Warm orange/yellow tint, vintage light leaks, high exposure, soft focus.",
        "thumbnail": "style_sunset_beach_film.jpg",
        "bg_gradient": ((45, 15, 20), (155, 65, 35)),
        "face_tint": (1.15, 0.95, 0.8),
        "brightness": 1.05,
        "contrast": 0.95,
        "saturation": 1.1,
        "special_effect": None,
        "overlay": "light_leak",
        "frame": None,
        "overlay_text": "MALIBU DREAMS",
        "overlay_subtext": "SUMMER SOLSTICE"
    },
    {
        "id": "golden_hour_romance",
        "name": "Golden Hour Romance",
        "category": "Cinematic",
        "description": "Sun-drenched romance with long shadows and warm, glowing rim light.",
        "use_cases": "Fields of gold, sunset backdrops, warm close-ups.",
        "visual_treatment": "Deep amber color grading, bright highlights, lens flare, soft skin glow.",
        "thumbnail": "style_golden_hour_romance.jpg",
        "bg_gradient": ((50, 25, 15), (175, 95, 40)),
        "face_tint": (1.18, 1.0, 0.78),
        "brightness": 1.0,
        "contrast": 1.0,
        "saturation": 1.15,
        "special_effect": None,
        "overlay": "light_leak",
        "frame": None,
        "overlay_text": "GOLDEN HOUR",
        "overlay_subtext": "CAPTURED GLOW"
    },
    {
        "id": "rainy_movie_scene",
        "name": "Rainy Movie Scene",
        "category": "Cinematic",
        "description": "Dramatic movie-like rainy atmosphere with reflections and glowing neon lights.",
        "use_cases": "Under-umbrella close-ups, city streets at night, moody winter shoots.",
        "visual_treatment": "Cool blue-green palette, heavy droplet overlays, high reflection gloss.",
        "thumbnail": "style_rainy_movie_scene.jpg",
        "bg_gradient": ((5, 10, 20), (30, 45, 65)),
        "face_tint": (0.85, 0.95, 1.1),
        "brightness": 0.88,
        "contrast": 1.1,
        "saturation": 0.95,
        "special_effect": None,
        "overlay": "rain",
        "frame": None,
        "overlay_text": "MIDNIGHT SHOWER",
        "overlay_subtext": "UNDER THE RAIN"
    },

    # ==========================================
    # FANTASY CATEGORY (10 Presets)
    # ==========================================
    {
        "id": "fairytale",
        "name": "Fairytale Fantasy",
        "category": "Fantasy",
        "description": "Enchanted forest magic with soft bioluminescent particles and dreamlike focus.",
        "use_cases": "Fanciful mystical backdrops, magical gowns, ethereal couple shoots.",
        "visual_treatment": "Bioluminescent sparkles, purple/blue mist, soft focus blending.",
        "thumbnail": "style_fairytale.jpg",
        "bg_gradient": ((30, 15, 45), (100, 60, 130)),
        "face_tint": (1.05, 0.95, 1.15),
        "brightness": 1.02,
        "contrast": 0.95,
        "saturation": 1.3,
        "special_effect": None,
        "overlay": "sparkles",
        "frame": None,
        "overlay_text": None,
        "overlay_subtext": None
    },
    {
        "id": "gothic",
        "name": "Gothic Victorian",
        "category": "Fantasy",
        "description": "Moody dark candlelight with vintage lace overlays and deep crimson tones.",
        "use_cases": "Halloween shoots, dark-themed styling, medieval architecture.",
        "visual_treatment": "Deep shadow vignetting, cold desaturated skin, candlelight amber glows.",
        "thumbnail": "style_gothic.jpg",
        "bg_gradient": ((10, 3, 5), (50, 15, 20)),
        "face_tint": (0.9, 0.85, 0.95),
        "brightness": 0.75,
        "contrast": 1.25,
        "saturation": 0.8,
        "special_effect": None,
        "overlay": "vignette",
        "frame": None,
        "overlay_text": "VICTORIAN GOTHIC",
        "overlay_subtext": "ETERNAL LOVE"
    },
    {
        "id": "enchanted_kingdom",
        "name": "Enchanted Kingdom",
        "category": "Fantasy",
        "description": "Majestic medieval castle courtyard backdrop with magical sun rays.",
        "use_cases": "Royal armors, grand capes, high fantasy costumes.",
        "visual_treatment": "God-rays overlay, volumetric light beam filter, stone castle details, rich gold tint.",
        "thumbnail": "style_enchanted_kingdom.jpg",
        "bg_gradient": ((25, 20, 15), (75, 65, 50)),
        "face_tint": (1.08, 1.02, 0.92),
        "brightness": 1.05,
        "contrast": 1.1,
        "saturation": 1.05,
        "special_effect": None,
        "overlay": "sunlight",
        "frame": None,
        "overlay_text": "ROYAL FEALTY",
        "overlay_subtext": "CASTLE CHRONICLES"
    },
    {
        "id": "fairy_forest",
        "name": "Fairy Forest",
        "category": "Fantasy",
        "description": "Lush glowing wilderness filled with mossy trees and small magical wisps.",
        "use_cases": "Natural outdoor settings, light flowy dresses, woodland settings.",
        "visual_treatment": "Intense green/emerald tones, yellow fairy wisps, soft fantasy glow.",
        "thumbnail": "style_fairy_forest.jpg",
        "bg_gradient": ((10, 35, 15), (45, 95, 55)),
        "face_tint": (1.02, 1.08, 0.98),
        "brightness": 1.02,
        "contrast": 1.0,
        "saturation": 1.2,
        "special_effect": None,
        "overlay": "wisps",
        "frame": None,
        "overlay_text": "FAIRY WOODS",
        "overlay_subtext": "DEEP FOREST MYSTERY"
    },
    {
        "id": "angelic_romance",
        "name": "Angelic Romance",
        "category": "Fantasy",
        "description": "Heavenly clouds preset with glowing halo elements and white feathered wings.",
        "use_cases": "Ethereal couples, cloudscapes, white and pastel color schemes.",
        "visual_treatment": "High-key white glow, feathery overlays, halo lights, light blue tint.",
        "thumbnail": "style_angelic_romance.jpg",
        "bg_gradient": ((210, 235, 250), (255, 255, 255)),
        "face_tint": (1.02, 1.02, 1.08),
        "brightness": 1.15,
        "contrast": 0.9,
        "saturation": 0.85,
        "special_effect": None,
        "overlay": "sparkles",
        "frame": None,
        "overlay_text": "SERAPHIC BOND",
        "overlay_subtext": "HEAVENLY PLACES"
    },
    {
        "id": "moonlight_magic",
        "name": "Moonlight Magic",
        "category": "Fantasy",
        "description": "Mystical night romance illuminated by a massive full moon.",
        "use_cases": "Silhouetted couples, starry night backdrops, deep blue outfits.",
        "visual_treatment": "Deep navy grading, moon glow rim-light, silver reflections, high-contrast sky.",
        "thumbnail": "style_moonlight_magic.jpg",
        "bg_gradient": ((3, 8, 25), (15, 30, 75)),
        "face_tint": (0.88, 0.98, 1.12),
        "brightness": 0.85,
        "contrast": 1.15,
        "saturation": 0.9,
        "special_effect": None,
        "overlay": "vignette",
        "frame": None,
        "overlay_text": "MOONLIGHT PATH",
        "overlay_subtext": "SILVER RAYS"
    },
    {
        "id": "celestial_lovers",
        "name": "Celestial Lovers",
        "category": "Fantasy",
        "description": "Cosmic space backdrop with nebulae, glowing stardust, and constellation trails.",
        "use_cases": "Astro-photography styles, sci-fi themes, dreamscapes.",
        "visual_treatment": "Space-dust overlays, purple/magenta cosmic gas colors, starry sparkles, high saturation.",
        "thumbnail": "style_celestial_lovers.jpg",
        "bg_gradient": ((15, 5, 30), (75, 25, 120)),
        "face_tint": (0.95, 0.9, 1.15),
        "brightness": 1.0,
        "contrast": 1.2,
        "saturation": 1.25,
        "special_effect": None,
        "overlay": "sparkles",
        "frame": None,
        "overlay_text": "STARDUST COUPLE",
        "overlay_subtext": "WRITTEN IN THE STARS"
    },
    {
        "id": "dragon_fantasy",
        "name": "Dragon Fantasy",
        "category": "Fantasy",
        "description": "Dramatic epic fantasy with glowing embers, volcanic backdrops, and dragon silhouettes.",
        "use_cases": "Dark fantasy styles, high-contrast fantasy armor, fire themes.",
        "visual_treatment": "Molten red/orange gradients, ember particle overlays, smoke textures, dramatic shadows.",
        "thumbnail": "style_dragon_fantasy.jpg",
        "bg_gradient": ((25, 5, 0), (95, 25, 10)),
        "face_tint": (1.18, 0.92, 0.85),
        "brightness": 0.9,
        "contrast": 1.25,
        "saturation": 1.2,
        "special_effect": None,
        "overlay": "light_leak",
        "frame": None,
        "overlay_text": "WYRM RIDER",
        "overlay_subtext": "FIERY COVENANT"
    },
    {
        "id": "elven_kingdom",
        "name": "Elven Kingdom",
        "category": "Fantasy",
        "description": "Ancient magical forest city with glowing white marble architecture and elegant arches.",
        "use_cases": "Elegant fantasy robes, silver hair styles, beautiful garden settings.",
        "visual_treatment": "High-exposure whites, silver leaf overlays, soft warm highlights, emerald shadows.",
        "thumbnail": "style_elven_kingdom.jpg",
        "bg_gradient": ((20, 40, 30), (100, 140, 120)),
        "face_tint": (1.04, 1.06, 1.02),
        "brightness": 1.08,
        "contrast": 0.92,
        "saturation": 1.0,
        "special_effect": None,
        "overlay": "sunlight",
        "frame": None,
        "overlay_text": "VALLEY OF ELVES",
        "overlay_subtext": "IMMORTAL EMBRACE"
    },
    {
        "id": "magical_castle",
        "name": "Magical Castle",
        "category": "Fantasy",
        "description": "Dreamy fantasy castle landscape with floating islands and rainbow light trails.",
        "use_cases": "Whimsical fairytale ideas, cosplay, imaginative couple shoots.",
        "visual_treatment": "Rainbow lens effects, cloud texture blending, high-key pastel colors.",
        "thumbnail": "style_magical_castle.jpg",
        "bg_gradient": ((40, 20, 60), (140, 90, 180)),
        "face_tint": (1.08, 0.98, 1.1),
        "brightness": 1.1,
        "contrast": 0.95,
        "saturation": 1.2,
        "special_effect": None,
        "overlay": "sparkles",
        "frame": None,
        "overlay_text": "AETHER CASTLE",
        "overlay_subtext": "FLOATING ISLANDS"
    },

    # ==========================================
    # WEDDING CATEGORY (8 Presets)
    # ==========================================
    {
        "id": "wedding",
        "name": "Wedding Photoshoot",
        "category": "Wedding",
        "description": "Classic soft glowing romantic atmosphere with rose and gold hues.",
        "use_cases": "Traditional bridal couples, ceremony shots, engagement announcements.",
        "visual_treatment": "Soft contrast, pink and gold tints, glowing skin filters, dreamy highlights.",
        "thumbnail": "style_wedding.jpg",
        "bg_gradient": ((50, 40, 45), (120, 100, 105)),
        "face_tint": (1.05, 1.02, 1.05),
        "brightness": 1.1,
        "contrast": 0.85,
        "saturation": 1.0,
        "special_effect": None,
        "overlay": "light_leak",
        "frame": None,
        "overlay_text": None,
        "overlay_subtext": None
    },
    {
        "id": "royal_wedding",
        "name": "Royal Wedding",
        "category": "Wedding",
        "description": "Ultra-luxurious, grand palace wedding photography with gold accents.",
        "use_cases": "Ornate traditional bridal wears, palace or cathedral backdrops.",
        "visual_treatment": "Ornate gold border, warm saturation, high sharpness, rich jewel-tone depth.",
        "thumbnail": "style_royal_wedding.jpg",
        "bg_gradient": ((45, 10, 15), (110, 30, 45)),
        "face_tint": (1.08, 1.04, 0.94),
        "brightness": 1.02,
        "contrast": 1.1,
        "saturation": 1.15,
        "special_effect": None,
        "overlay": "vignette",
        "frame": "gold_foil",
        "overlay_text": "ROYAL MATRIMONY",
        "overlay_subtext": "AN EMPIRE'S CELEBRATION"
    },
    {
        "id": "luxury_bridal",
        "name": "Luxury Bridal Shoot",
        "category": "Wedding",
        "description": "High-fashion editorial bridal layout featuring clean, high-key lighting.",
        "use_cases": "Modern white gown bridal shoots, indoor studio wedding poses.",
        "visual_treatment": "Bright exposure, crisp whites, minimal shadows, subtle silver-toning.",
        "thumbnail": "style_luxury_bridal.jpg",
        "bg_gradient": ((235, 235, 235), (255, 255, 255)),
        "face_tint": (1.02, 1.02, 1.05),
        "brightness": 1.18,
        "contrast": 0.95,
        "saturation": 0.9,
        "special_effect": None,
        "overlay": "vignette",
        "frame": None,
        "overlay_text": "BRIDAL GLAMOUR",
        "overlay_subtext": "VOGUE WEDDINGS"
    },
    {
        "id": "destination_wedding",
        "name": "Destination Wedding",
        "category": "Wedding",
        "description": "Luminous and airy wedding style captured in exotic natural landmarks.",
        "use_cases": "Seaside cliffs, mountain ridges, sandy beaches, light pastel attire.",
        "visual_treatment": "High brightness, pastel sky coloring, low saturation of greens/blues, soft shadows.",
        "thumbnail": "style_destination_wedding.jpg",
        "bg_gradient": ((190, 225, 235), (255, 245, 230)),
        "face_tint": (1.04, 1.02, 1.0),
        "brightness": 1.12,
        "contrast": 0.9,
        "saturation": 0.95,
        "special_effect": None,
        "overlay": "sunlight",
        "frame": None,
        "overlay_text": "DESTINATION LOVE",
        "overlay_subtext": "SAYING I DO"
    },
    {
        "id": "beach_wedding",
        "name": "Beach Wedding",
        "category": "Wedding",
        "description": "Sun-kissed, tropical coastal wedding style with warm sand and turquoise sea tones.",
        "use_cases": "Beachfront ceremonies, casual flowy wedding attire, sunset beach walk.",
        "visual_treatment": "Teal-and-tan color matching, bright warm sand exposure, warm light leakage.",
        "thumbnail": "style_beach_wedding.jpg",
        "bg_gradient": ((30, 95, 115), (225, 185, 140)),
        "face_tint": (1.1, 1.0, 0.9),
        "brightness": 1.08,
        "contrast": 1.0,
        "saturation": 1.1,
        "special_effect": None,
        "overlay": "light_leak",
        "frame": None,
        "overlay_text": "SEASIDE VOWS",
        "overlay_subtext": "OCEAN TIDES"
    },
    {
        "id": "christian_wedding",
        "name": "Christian Wedding",
        "category": "Wedding",
        "description": "Classic white chapel wedding aesthetic with stained glass light filtering.",
        "use_cases": "Traditional white wedding dresses, chapel interior, elegant bouquets.",
        "visual_treatment": "Soft glow, backlighting simulation, cool white balancing, gold-rimmed highlights.",
        "thumbnail": "style_christian_wedding.jpg",
        "bg_gradient": ((180, 200, 220), (250, 250, 250)),
        "face_tint": (1.0, 1.02, 1.08),
        "brightness": 1.06,
        "contrast": 0.95,
        "saturation": 0.9,
        "special_effect": None,
        "overlay": "sunlight",
        "frame": None,
        "overlay_text": "SACRED COVENANT",
        "overlay_subtext": "IN HOLY MATRIMONY"
    },
    {
        "id": "garden_wedding",
        "name": "Garden Wedding",
        "category": "Wedding",
        "description": "Charming, rustic outdoor wedding style with lush floral and green highlights.",
        "use_cases": "Flower arches, botanical garden settings, boho wedding outfits.",
        "visual_treatment": "Warm botanical color filters, high green saturation, dreamy bokeh overlays.",
        "thumbnail": "style_garden_wedding.jpg",
        "bg_gradient": ((40, 75, 45), (145, 180, 130)),
        "face_tint": (1.05, 1.05, 0.95),
        "brightness": 1.05,
        "contrast": 0.98,
        "saturation": 1.15,
        "special_effect": None,
        "overlay": "wisps",
        "frame": None,
        "overlay_text": "GARDEN CEREMONY",
        "overlay_subtext": "BLOOMING LOVE"
    },
    {
        "id": "fairytale_wedding",
        "name": "Fairytale Wedding",
        "category": "Wedding",
        "description": "Enchanted forest wedding look with magical fairy lights and mystical fog.",
        "use_cases": "Dense forest paths, night wedding lights, fantasy themed celebrations.",
        "visual_treatment": "Violet and amber tinting, heavy glow, starburst sparkles, mystical mist overlay.",
        "thumbnail": "style_fairytale_wedding.jpg",
        "bg_gradient": ((50, 30, 70), (130, 80, 150)),
        "face_tint": (1.06, 0.98, 1.08),
        "brightness": 1.02,
        "contrast": 1.0,
        "saturation": 1.2,
        "special_effect": None,
        "overlay": "sparkles",
        "frame": None,
        "overlay_text": "ONCE UPON A TIME",
        "overlay_subtext": "HAPPY EVER AFTER"
    },

    # ==========================================
    # VINTAGE CATEGORY (5 Presets)
    # ==========================================
    {
        "id": "vintage",
        "name": "Vintage Retro (70s/80s)",
        "category": "Vintage",
        "description": "Sepia-tinged coloring with analog timestamp overlays and warm 70s print grain.",
        "use_cases": "Retro outfits, vinyl record store settings, nostalgic couple photos.",
        "visual_treatment": "Sepia/yellowish tint, border styling, timestamp text, heavy analog noise.",
        "thumbnail": "style_vintage.jpg",
        "bg_gradient": ((60, 50, 40), (135, 115, 95)),
        "face_tint": (1.15, 0.95, 0.75),
        "brightness": 0.95,
        "contrast": 1.15,
        "saturation": 0.55,
        "special_effect": None,
        "overlay": "film_grain",
        "frame": "vintage_border",
        "overlay_text": "RECORDED 1978",
        "overlay_subtext": "VINTAGE MEMORY"
    },
    {
        "id": "vintage_polaroid",
        "name": "Vintage Polaroid",
        "category": "Vintage",
        "description": "Instant film print effect with a classic white Polaroid frame and vintage low-fidelity colors.",
        "use_cases": "Candid snapshots, beach trips, casual daily couple moments.",
        "visual_treatment": "Polaroid border frame, faded black point, high color warmth, vintage low contrast.",
        "thumbnail": "style_vintage_polaroid.jpg",
        "bg_gradient": ((200, 195, 185), (235, 230, 220)),
        "face_tint": (1.12, 1.0, 0.88),
        "brightness": 1.02,
        "contrast": 0.85,
        "saturation": 0.75,
        "special_effect": None,
        "overlay": "film_grain",
        "frame": "Polaroid",
        "overlay_text": "SUMMER '85",
        "overlay_subtext": "INSTANT MEMORY"
    },
    {
        "id": "film_noir",
        "name": "Vintage Film Noir",
        "category": "Vintage",
        "description": "Dramatic 1940s black and white detective film look with shadow blind patterns.",
        "use_cases": "Suits and trench coats, city streetlights at night, high-drama expressions.",
        "visual_treatment": "Monochrome conversion, shadow-blind texture overlay, high contrast, film grain.",
        "thumbnail": "style_film_noir.jpg",
        "bg_gradient": ((5, 5, 5), (45, 45, 45)),
        "face_tint": (0.9, 0.9, 0.9),
        "brightness": 0.8,
        "contrast": 1.4,
        "saturation": 0.0,
        "special_effect": "grayscale",
        "overlay": "film_grain",
        "frame": None,
        "overlay_text": "THE LAST EMBRACE",
        "overlay_subtext": "FILM NOIR"
    },
    {
        "id": "old_hollywood",
        "name": "Old Hollywood B&W",
        "category": "Vintage",
        "description": "Classic 1930s glamor portrait style with soft focus, glow, and deep shadows.",
        "use_cases": "Classic dresses, tuxedo styling, formal retro poses.",
        "visual_treatment": "Soft black-and-white tint, glow filter (diffusion), high-contrast glamor lighting.",
        "thumbnail": "style_old_hollywood.jpg",
        "bg_gradient": ((8, 8, 8), (50, 50, 50)),
        "face_tint": (0.95, 0.95, 0.95),
        "brightness": 0.9,
        "contrast": 1.25,
        "saturation": 0.0,
        "special_effect": "grayscale",
        "overlay": "vignette",
        "frame": None,
        "overlay_text": "GOLDEN AGE",
        "overlay_subtext": "STUDIO ONE"
    },
    {
        "id": "retro_neon_80s",
        "name": "Retro 80s Neon",
        "category": "Vintage",
        "description": "Vaporwave-inspired 1980s neon look with scanlines and VHS glitches.",
        "use_cases": "Neon signage backdrops, leather jackets, arcade date themes.",
        "visual_treatment": "Scanlines, pink-blue chromatic aberration, neon flares, VHS distortion overlays.",
        "thumbnail": "style_retro_neon_80s.jpg",
        "bg_gradient": ((10, 0, 20), (50, 5, 80)),
        "face_tint": (0.9, 1.1, 1.2),
        "brightness": 1.05,
        "contrast": 1.2,
        "saturation": 1.35,
        "special_effect": None,
        "overlay": "grid",
        "frame": None,
        "overlay_text": "NEON RIDER",
        "overlay_subtext": "VHS RETRO 1988"
    },

    # ==========================================
    # ANIME CATEGORY (8 Presets)
    # ==========================================
    {
        "id": "anime",
        "name": "Anime-Inspired",
        "category": "Anime",
        "description": "Stylized hand-drawn outlines, posterized color fields, and beautiful saturated sky backdrops.",
        "use_cases": "Casual day-out portraits, vibrant colorful styling, cartoon representations.",
        "visual_treatment": "Posterization filter, black pencil outlines, sky gradient mapping.",
        "thumbnail": "style_anime.jpg",
        "bg_gradient": ((230, 240, 255), (150, 190, 235)),
        "face_tint": (1.05, 1.05, 1.05),
        "brightness": 1.0,
        "contrast": 1.0,
        "saturation": 1.0,
        "special_effect": "posterize",
        "overlay": None,
        "frame": None,
        "overlay_text": None,
        "overlay_subtext": None
    },
    {
        "id": "ghibli_inspired",
        "name": "Studio Ghibli Inspired",
        "category": "Anime",
        "description": "Whimsical hand-painted watercolor skies and grassy meadow backdrops.",
        "use_cases": "Grassy hills, sunny meadows, flowy spring outfits, dreamlike anime feel.",
        "visual_treatment": "Painterly brush-stroke textures, warm gouache colors, soft outlines, blue-green bias.",
        "thumbnail": "style_ghibli_inspired.jpg",
        "bg_gradient": ((135, 200, 160), (180, 220, 240)),
        "face_tint": (1.06, 1.04, 0.98),
        "brightness": 1.05,
        "contrast": 0.95,
        "saturation": 1.2,
        "special_effect": "posterize",
        "overlay": "wisps",
        "frame": None,
        "overlay_text": "WINDY MEADOW",
        "overlay_subtext": "STUDIO GHIBLI RETRIBUTE"
    },
    {
        "id": "shonen_anime",
        "name": "Shonen Anime",
        "category": "Anime",
        "description": "Dynamic action anime style with speed-lines and glowing power auras.",
        "use_cases": "Playful battle poses, energetic expressions, anime-con outfits.",
        "visual_treatment": "Radial speed lines overlay, glowing aura outline, high energy contrast, cel-shading.",
        "thumbnail": "style_shonen_anime.jpg",
        "bg_gradient": ((20, 20, 30), (70, 70, 120)),
        "face_tint": (1.08, 1.0, 1.08),
        "brightness": 1.1,
        "contrast": 1.3,
        "saturation": 1.25,
        "special_effect": "posterize",
        "overlay": "grid",
        "frame": None,
        "overlay_text": "POWER LEVEL 9000",
        "overlay_subtext": "EPISODE 1: WAKING UP"
    },
    {
        "id": "kawaii_romance",
        "name": "Kawaii Romance",
        "category": "Anime",
        "description": "Charming and cute anime style with pastel pink tones, hearts, and sparkle overlays.",
        "use_cases": "Playful couple photos, school uniform shoots, candy store backdrops.",
        "visual_treatment": "Blush cheek overlays, cute pink/pastel filters, floating heart particles, soft glow.",
        "thumbnail": "style_kawaii_romance.jpg",
        "bg_gradient": ((255, 230, 240), (255, 200, 220)),
        "face_tint": (1.1, 1.0, 1.05),
        "brightness": 1.08,
        "contrast": 0.9,
        "saturation": 1.15,
        "special_effect": "posterize",
        "overlay": "sparkles",
        "frame": None,
        "overlay_text": "K A W A I I",
        "overlay_subtext": "S P A R K L E  L O V E"
    },
    {
        "id": "anime_poster",
        "name": "Anime Movie Poster",
        "category": "Anime",
        "description": "Epic modern anime feature film look with sunset skies and cinematic Japanese subtitles.",
        "use_cases": "Scenic mountain-top background, deep sky, emotional couple portraits.",
        "visual_treatment": "Japanese film-style text overlay, saturated orange-violet clouds, high contrast shadows.",
        "thumbnail": "style_anime_poster.jpg",
        "bg_gradient": ((40, 20, 60), (220, 100, 80)),
        "face_tint": (1.08, 1.02, 0.95),
        "brightness": 1.02,
        "contrast": 1.1,
        "saturation": 1.2,
        "special_effect": "posterize",
        "overlay": "sunlight",
        "frame": None,
        "overlay_text": "君の愛は。(YOUR LOVE)",
        "overlay_subtext": "A CINEMA ART WORK"
    },
    {
        "id": "manga_art",
        "name": "Manga Art",
        "category": "Anime",
        "description": "Classic ink-drawn black and white manga page style with screen-tone dots.",
        "use_cases": "Comic book fans, high-contrast graphic novel poses.",
        "visual_treatment": "Halftone dots filter, black ink outlines, speed lines, high contrast monochrome.",
        "thumbnail": "style_manga_art.jpg",
        "bg_gradient": ((250, 250, 250), (210, 210, 210)),
        "face_tint": (0.9, 0.9, 0.9),
        "brightness": 1.0,
        "contrast": 1.5,
        "saturation": 0.0,
        "special_effect": "grayscale",
        "overlay": "grid",
        "frame": None,
        "overlay_text": "CHAPTER 12: CONFESSION",
        "overlay_subtext": "TO BE CONTINUED..."
    },
    {
        "id": "sakura_romance",
        "name": "Sakura Romance",
        "category": "Anime",
        "description": "Dreamy anime romance scene filled with falling pink cherry blossom petals.",
        "use_cases": "Spring portraits, school pathways, cherry blossom garden settings.",
        "visual_treatment": "Falling sakura petal overlays, pink pastel color grade, dreamlike soft focus.",
        "thumbnail": "style_sakura_romance.jpg",
        "bg_gradient": ((255, 235, 240), (245, 180, 200)),
        "face_tint": (1.08, 1.0, 1.04),
        "brightness": 1.06,
        "contrast": 0.95,
        "saturation": 1.1,
        "special_effect": "posterize",
        "overlay": "sakura",
        "frame": None,
        "overlay_text": "SAKURA BLOSSOMS",
        "overlay_subtext": "SPRINGTIME CONFESSION"
    },
    {
        "id": "fantasy_anime",
        "name": "Fantasy Anime",
        "category": "Anime",
        "description": "Otherworldly anime world with glowing magical symbols and cosmic stardust skies.",
        "use_cases": "Magical girl/boy themes, starry night backdrops, cosmic anime cosplays.",
        "visual_treatment": "Starry sky replacement, neon magic circle overlays, high saturation.",
        "thumbnail": "style_fantasy_anime.jpg",
        "bg_gradient": ((15, 10, 35), (90, 45, 140)),
        "face_tint": (1.02, 0.98, 1.1),
        "brightness": 1.04,
        "contrast": 1.15,
        "saturation": 1.3,
        "special_effect": "posterize",
        "overlay": "sparkles",
        "frame": None,
        "overlay_text": "MAGIC RITUAL",
        "overlay_subtext": "FANTASY GATEWAY"
    },

    # ==========================================
    # LUXURY CATEGORY (8 Presets)
    # ==========================================
    {
        "id": "vogue_editorial",
        "name": "Vogue Editorial",
        "category": "Luxury",
        "description": "High-fashion model photography look with sleek high-contrast studio light.",
        "use_cases": "Tailored suits, evening gowns, sharp high-fashion portraiture.",
        "visual_treatment": "High contrast, silver-grey color grading, sharp details, minimal warm tones.",
        "thumbnail": "style_vogue_editorial.jpg",
        "bg_gradient": ((15, 15, 15), (70, 70, 70)),
        "face_tint": (1.0, 1.0, 1.02),
        "brightness": 0.95,
        "contrast": 1.25,
        "saturation": 0.75,
        "special_effect": None,
        "overlay": "vignette",
        "frame": None,
        "overlay_text": "V O G U E",
        "overlay_subtext": "EDITORIAL SPECIAL"
    },
    {
        "id": "fashion_magazine",
        "name": "Fashion Magazine Cover",
        "category": "Luxury",
        "description": "Stylish magazine mock with bold header text, borders, and modern studio flash.",
        "use_cases": "Glamorous couples, high-key studio edits, portfolio headers.",
        "visual_treatment": "Cover text overlays, modern border layouts, cool skin tones, crisp details.",
        "thumbnail": "style_fashion_magazine.jpg",
        "bg_gradient": ((245, 245, 245), (255, 255, 255)),
        "face_tint": (1.02, 1.02, 1.04),
        "brightness": 1.12,
        "contrast": 1.1,
        "saturation": 1.05,
        "special_effect": None,
        "overlay": "vignette",
        "frame": "magazine_border",
        "overlay_text": "MODERN COUPLES",
        "overlay_subtext": "STYLE ISSUE 2026"
    },
    {
        "id": "yacht_romance",
        "name": "Luxury Yacht Romance",
        "category": "Luxury",
        "description": "Jet-setter lifestyle aesthetic featuring sunny yacht decks and deep blue ocean views.",
        "use_cases": "Summer travel, white linen outfits, sunglasses-clad couple poses.",
        "visual_treatment": "High brightness, deep sea blue enhancement, warm gold sunshine flare.",
        "thumbnail": "style_yacht_romance.jpg",
        "bg_gradient": ((12, 60, 95), (200, 220, 235)),
        "face_tint": (1.02, 1.02, 0.98),
        "brightness": 1.1,
        "contrast": 1.05,
        "saturation": 1.15,
        "special_effect": None,
        "overlay": "sunlight",
        "frame": None,
        "overlay_text": "YACHT LIFE",
        "overlay_subtext": "OFF THE RIVIERA COAST"
    },
    {
        "id": "monaco_lifestyle",
        "name": "Monaco Lifestyle",
        "category": "Luxury",
        "description": "High-end European Riviera look with luxury sports cars and casino backdrops.",
        "use_cases": "Classy outfits, elite night outings, exotic sports car shoots.",
        "visual_treatment": "Warm desaturated tones, deep blacks, high-end film stock emulation, subtle gold grading.",
        "thumbnail": "style_monaco_lifestyle.jpg",
        "bg_gradient": ((20, 18, 15), (75, 65, 55)),
        "face_tint": (1.05, 1.0, 0.95),
        "brightness": 0.92,
        "contrast": 1.15,
        "saturation": 0.85,
        "special_effect": None,
        "overlay": "film_grain",
        "frame": None,
        "overlay_text": "MONACO GRAND",
        "overlay_subtext": "CASINO ROYALE"
    },
    {
        "id": "billionaire_couple",
        "name": "Billionaire Couple",
        "category": "Luxury",
        "description": "Opulent lifestyle theme with private jet runways and executive lounge backdrops.",
        "use_cases": "Business formal suits, designer outfits, travel-luxe scenes.",
        "visual_treatment": "Low-saturation luxury coloring, deep shadows, crisp details, cool corporate tint.",
        "thumbnail": "style_billionaire_couple.jpg",
        "bg_gradient": ((10, 15, 20), (55, 65, 75)),
        "face_tint": (1.0, 1.02, 1.02),
        "brightness": 1.0,
        "contrast": 1.1,
        "saturation": 0.8,
        "special_effect": None,
        "overlay": "vignette",
        "frame": None,
        "overlay_text": "EXECUTIVE TRAVEL",
        "overlay_subtext": "GLOBAL CONCIERGE"
    },
    {
        "id": "red_carpet",
        "name": "Red Carpet Event",
        "category": "Luxury",
        "description": "Glamorous awards night scene with paparazzi flashbulbs and red carpet entry.",
        "use_cases": "Designer evening gowns, celebrity-look couple poses, award ceremonies.",
        "visual_treatment": "Red-glow color grading, white flashbulb sparkles, high-key dramatic lighting.",
        "thumbnail": "style_red_carpet.jpg",
        "bg_gradient": ((50, 5, 10), (120, 15, 20)),
        "face_tint": (1.08, 1.0, 0.95),
        "brightness": 1.06,
        "contrast": 1.2,
        "saturation": 1.2,
        "special_effect": None,
        "overlay": "sparkles",
        "frame": None,
        "overlay_text": "AWARDS GALA",
        "overlay_subtext": "RED CARPET INTERVIEW"
    },
    {
        "id": "luxury_penthouse",
        "name": "Luxury Penthouse",
        "category": "Luxury",
        "description": "Elegant indoor setting overlooking a sprawling modern city skyline at night.",
        "use_cases": "Sleek lounge wear, cocktail dresses, cityscape windows.",
        "visual_treatment": "High dynamic range, warm indoor lights versus cool city neon windows, soft glow.",
        "thumbnail": "style_luxury_penthouse.jpg",
        "bg_gradient": ((12, 12, 22), (60, 45, 90)),
        "face_tint": (1.06, 1.02, 0.98),
        "brightness": 1.04,
        "contrast": 1.08,
        "saturation": 1.1,
        "special_effect": None,
        "overlay": "light_leak",
        "frame": None,
        "overlay_text": "PENTHOUSE VIEW",
        "overlay_subtext": "52ND FLOOR RETREAT"
    },
    {
        "id": "designer_campaign",
        "name": "Designer Campaign",
        "category": "Luxury",
        "description": "Minimalist luxury brand campaign look with muted earth tones and clean shadows.",
        "use_cases": "Designer bag/watch accessories, beige/cream outfits, high-concept model portraits.",
        "visual_treatment": "Beige/warm-grey monochrome wash, low saturation, high grain, matte finish.",
        "thumbnail": "style_designer_campaign.jpg",
        "bg_gradient": ((110, 105, 95), (170, 165, 155)),
        "face_tint": (1.04, 1.02, 0.98),
        "brightness": 0.98,
        "contrast": 0.9,
        "saturation": 0.5,
        "special_effect": None,
        "overlay": "film_grain",
        "frame": None,
        "overlay_text": "COLLECTION 2026",
        "overlay_subtext": "MINIMALIST DESIGN"
    },

    # ==========================================
    # TRAVEL CATEGORY (9 Presets)
    # ==========================================
    {
        "id": "travel",
        "name": "Luxury Travel Couple",
        "category": "Travel",
        "description": "Scenic high-class travel edits with famous cityscapes and landmark backdrops.",
        "use_cases": "Travel diaries, outdoor landmark shots, adventuring couples.",
        "visual_treatment": "Vibrant sky colors, high-contrast HDR processing, scenic background blend.",
        "thumbnail": "style_travel.jpg",
        "bg_gradient": ((15, 45, 65), (75, 120, 150)),
        "face_tint": (1.0, 1.05, 1.05),
        "brightness": 1.08,
        "contrast": 1.1,
        "saturation": 1.15,
        "special_effect": None,
        "overlay": "sunlight",
        "frame": None,
        "overlay_text": None,
        "overlay_subtext": None
    },
    {
        "id": "paris_romance",
        "name": "Paris Romance",
        "category": "Travel",
        "description": "Romantic Eiffel Tower sunset backdrop with classic French café vibes.",
        "use_cases": "Romantic travel photos, spring coats, café dates.",
        "visual_treatment": "Warm romantic film tone, soft rose-gold sky grade, Eiffel tower sunset background.",
        "thumbnail": "style_paris_romance.jpg",
        "bg_gradient": ((60, 40, 50), (180, 120, 110)),
        "face_tint": (1.06, 1.0, 0.98),
        "brightness": 1.04,
        "contrast": 1.0,
        "saturation": 1.05,
        "special_effect": None,
        "overlay": "light_leak",
        "frame": None,
        "overlay_text": "LOVE IN PARIS",
        "overlay_subtext": "SEINE RIVER WALK"
    },
    {
        "id": "venice_gondola",
        "name": "Venice Gondola",
        "category": "Travel",
        "description": "Scenic boat ride along historical Venice canals with glowing golden backlights.",
        "use_cases": "Boating poses, classic stripes, scenic canal backgrounds.",
        "visual_treatment": "Emerald-green water tinting, glowing light overlay, vintage Italian postcard look.",
        "thumbnail": "style_venice_gondola.jpg",
        "bg_gradient": ((10, 50, 45), (105, 130, 80)),
        "face_tint": (1.05, 1.02, 0.95),
        "brightness": 1.02,
        "contrast": 1.0,
        "saturation": 1.1,
        "special_effect": None,
        "overlay": "light_leak",
        "frame": None,
        "overlay_text": "VENETIAN GONDOLA",
        "overlay_subtext": "CANAL DI VENEZIA"
    },
    {
        "id": "santorini_sunset",
        "name": "Santorini Sunset",
        "category": "Travel",
        "description": "Stunning caldera sunset framing white-domed Greek villas and cobalt sea.",
        "use_cases": "White and blue outfits, summer travel edits, sunset shots.",
        "visual_treatment": "Vibrant Greek blue details, warm orange sun flare, high white brightness.",
        "thumbnail": "style_santorini_sunset.jpg",
        "bg_gradient": ((15, 75, 140), (245, 150, 80)),
        "face_tint": (1.08, 1.0, 0.92),
        "brightness": 1.1,
        "contrast": 1.05,
        "saturation": 1.2,
        "special_effect": None,
        "overlay": "light_leak",
        "frame": None,
        "overlay_text": "SANTORINI ESCAPE",
        "overlay_subtext": "CYCLADES SUNSET"
    },
    {
        "id": "swiss_alps",
        "name": "Swiss Alps",
        "category": "Travel",
        "description": "Scenic snow-capped mountains backdrop with cozy alpine cabin and wooden deck.",
        "use_cases": "Winter coats, knit sweaters, snow landscapes.",
        "visual_treatment": "High detail snow structures, warm cabin light contrast, crisp cold mountain grading.",
        "thumbnail": "style_swiss_alps.jpg",
        "bg_gradient": ((30, 55, 80), (180, 205, 235)),
        "face_tint": (0.96, 1.02, 1.08),
        "brightness": 1.05,
        "contrast": 1.12,
        "saturation": 0.95,
        "special_effect": None,
        "overlay": "snow",
        "frame": None,
        "overlay_text": "ALPINE CHALET",
        "overlay_subtext": "SWISS HIGHLANDS"
    },
    {
        "id": "dubai_luxury",
        "name": "Dubai Luxury",
        "category": "Travel",
        "description": "Futuristic skyscraper background under golden desert sky illumination.",
        "use_cases": "Glamorous high-rise views, gold/white dresses, modern cityscape locations.",
        "visual_treatment": "Warm golden sky mapping, high-definition glass/steel reflections, warm exposure.",
        "thumbnail": "style_dubai_luxury.jpg",
        "bg_gradient": ((60, 40, 20), (210, 160, 75)),
        "face_tint": (1.1, 1.02, 0.92),
        "brightness": 1.08,
        "contrast": 1.08,
        "saturation": 1.1,
        "special_effect": None,
        "overlay": "sunlight",
        "frame": None,
        "overlay_text": "DUBAI SKYLINES",
        "overlay_subtext": "GOLDEN DESERT WIND"
    },
    {
        "id": "tokyo_nights",
        "name": "Tokyo Nights",
        "category": "Travel",
        "description": "Cyber-neon city streets at night filled with colorful billboards and rain reflections.",
        "use_cases": "Modern streetwear, night photography, rainy neon themes.",
        "visual_treatment": "Highly saturated cyan/magenta lights, wet street reflection textures, high clarity.",
        "thumbnail": "style_tokyo_nights.jpg",
        "bg_gradient": ((5, 2, 18), (15, 10, 45)),
        "face_tint": (0.9, 1.05, 1.15),
        "brightness": 1.02,
        "contrast": 1.2,
        "saturation": 1.3,
        "special_effect": None,
        "overlay": "rain",
        "frame": None,
        "overlay_text": "SHIBUYA SHOWER",
        "overlay_subtext": "TOKYO NEON GLOW"
    },
    {
        "id": "maldives_paradise",
        "name": "Maldives Paradise",
        "category": "Travel",
        "description": "Overwater bungalows over shallow turquoise lagoons and white sand beaches.",
        "use_cases": "Swimwear, light linen clothing, summer beach couples.",
        "visual_treatment": "Ultra-saturated turquoise water grading, clean white sand balance, bright skies.",
        "thumbnail": "style_maldives_paradise.jpg",
        "bg_gradient": ((10, 130, 160), (225, 245, 250)),
        "face_tint": (1.02, 1.04, 1.0),
        "brightness": 1.14,
        "contrast": 1.02,
        "saturation": 1.25,
        "special_effect": None,
        "overlay": "sunlight",
        "frame": None,
        "overlay_text": "MALDIVIAN SHORES",
        "overlay_subtext": "LAGUNA RETREAT"
    },
    {
        "id": "new_york_love",
        "name": "New York Love Story",
        "category": "Travel",
        "description": "Classic Brooklyn Bridge skyline sunset scene with urban romantic tone.",
        "use_cases": "Autumn jackets, bridge walks, city skyscrapers backgrounds.",
        "visual_treatment": "Warm city light reflection, soft film grain, orange-gold sky grading.",
        "thumbnail": "style_new_york_love.jpg",
        "bg_gradient": ((40, 25, 30), (145, 90, 60)),
        "face_tint": (1.06, 1.0, 0.95),
        "brightness": 1.0,
        "contrast": 1.05,
        "saturation": 1.0,
        "special_effect": None,
        "overlay": "film_grain",
        "frame": None,
        "overlay_text": "NYC RETRO",
        "overlay_subtext": "EAST RIVER SUNSET"
    },

    # ==========================================
    # SEASONAL CATEGORY (4 Presets)
    # ==========================================
    {
        "id": "winter_wonderland",
        "name": "Winter Wonderland",
        "category": "Seasonal",
        "description": "Falling snow flurries and cool, clean winter color balancing.",
        "use_cases": "Cozy sweaters, coats, winter-themed couple portraits.",
        "visual_treatment": "Cool snow blue wash, falling snowflake overlay, soft skin warmth preservation.",
        "thumbnail": "style_winter.jpg",
        "bg_gradient": ((15, 35, 60), (120, 155, 195)),
        "face_tint": (0.9, 1.02, 1.12),
        "brightness": 1.05,
        "contrast": 1.15,
        "saturation": 0.9,
        "special_effect": None,
        "overlay": "snow",
        "frame": None,
        "overlay_text": None,
        "overlay_subtext": None
    },
    {
        "id": "autumn_warmth",
        "name": "Autumn Warmth",
        "category": "Seasonal",
        "description": "Beautiful fall leaves overlay with warm rustic orange and brown tones.",
        "use_cases": "Cozy knitwear, forest walks, pumpkin patches, warm sunset dates.",
        "visual_treatment": "Rustic orange grading, falling maple leaf overlays, soft warm lighting.",
        "thumbnail": "style_autumn_warmth.jpg",
        "bg_gradient": ((50, 20, 10), (135, 75, 30)),
        "face_tint": (1.12, 1.0, 0.88),
        "brightness": 1.02,
        "contrast": 1.05,
        "saturation": 1.25,
        "special_effect": None,
        "overlay": "leaves",
        "frame": None,
        "overlay_text": "AUTUMN LEAVES",
        "overlay_subtext": "FALL IN LOVE"
    },
    {
        "id": "spring_blossoms",
        "name": "Spring Blossoms",
        "category": "Seasonal",
        "description": "Flowery spring garden filled with pastel roses and beautiful glowing sunbeams.",
        "use_cases": "Lace outfits, spring dresses, botanical garden settings.",
        "visual_treatment": "Pastel color grading, pink floral overlays, sunbeams, high-key brightness.",
        "thumbnail": "style_spring_blossoms.jpg",
        "bg_gradient": ((245, 225, 230), (255, 255, 255)),
        "face_tint": (1.05, 1.05, 0.95),
        "brightness": 1.12,
        "contrast": 0.9,
        "saturation": 1.1,
        "special_effect": None,
        "overlay": "sakura",
        "frame": None,
        "overlay_text": "SPRINGTIME GARDEN",
        "overlay_subtext": "BLOOMING BRIGHT"
    },
    {
        "id": "summer_solstice",
        "name": "Summer Sunshine",
        "category": "Seasonal",
        "description": "Bright sunflower fields under radiant sunshine and vintage retro summer tones.",
        "use_cases": "Sunflower field backdrops, summer dresses, bright outdoor couples.",
        "visual_treatment": "Saturated yellows, high-exposure sunlight, vintage warm filters.",
        "thumbnail": "style_summer_solstice.jpg",
        "bg_gradient": ((120, 110, 30), (245, 220, 75)),
        "face_tint": (1.15, 1.02, 0.85),
        "brightness": 1.15,
        "contrast": 1.0,
        "saturation": 1.3,
        "special_effect": None,
        "overlay": "sunlight",
        "frame": None,
        "overlay_text": "SUMMER SOLSTICE",
        "overlay_subtext": "UNDER THE SUNSHINE"
    },

    # ==========================================
    # CULTURAL CATEGORY (4 Presets)
    # ==========================================
    {
        "id": "royal_traditional_indian",
        "name": "Royal Traditional Indian",
        "category": "Cultural",
        "description": "Rich gold borders, imperial palaces, and warm heritage cultural tones.",
        "use_cases": "Sherwani and Lehenga attire, festival cards, majestic royal wedding ideas.",
        "visual_treatment": "Double gold border, palace backdrops, warm cultural filters, rich saturation.",
        "thumbnail": "style_royal.jpg",
        "bg_gradient": ((50, 5, 15), (25, 20, 30)),
        "face_tint": (1.05, 1.05, 0.9),
        "brightness": 1.0,
        "contrast": 1.0,
        "saturation": 1.1,
        "special_effect": None,
        "overlay": "vignette",
        "frame": "gold_foil",
        "overlay_text": "A ROYAL PORTRAIT",
        "overlay_subtext": "HERITAGE OF INDIA"
    },
    {
        "id": "bollywood_poster",
        "name": "Bollywood Movie Poster",
        "category": "Cultural",
        "description": "Dramatic movie title text overlay and high contrast romantic cinema framing.",
        "use_cases": "Couples wearing traditional or dramatic movie outfits.",
        "visual_treatment": "Vintage movie fonts, filmic grain, red-orange warm tint, vignette.",
        "thumbnail": "style_bollywood.jpg",
        "bg_gradient": ((30, 5, 5), (110, 50, 15)),
        "face_tint": (1.1, 0.95, 0.85),
        "brightness": 0.95,
        "contrast": 1.1,
        "saturation": 1.0,
        "special_effect": None,
        "overlay": "film_grain",
        "frame": None,
        "overlay_text": "H A M S A F A R",
        "overlay_subtext": "A BOLLYWOOD ROMANCE"
    },
    {
        "id": "traditional_indian_wedding",
        "name": "Traditional Indian Wedding",
        "category": "Cultural",
        "description": "Grand mandap backdrop with marigold floral designs and warm fire illumination.",
        "use_cases": "Traditional Indian wedding outfits, festive couple portraits.",
        "visual_treatment": "Marigold garland borders, bright gold/red color grade, warm fire glow, high clarity.",
        "thumbnail": "style_traditional_indian_wedding.jpg",
        "bg_gradient": ((60, 10, 15), (150, 45, 20)),
        "face_tint": (1.1, 1.05, 0.88),
        "brightness": 1.05,
        "contrast": 1.12,
        "saturation": 1.25,
        "special_effect": None,
        "overlay": "sparkles",
        "frame": "mandap_border",
        "overlay_text": "SHUBH VIVAH",
        "overlay_subtext": "VOWS BY THE HOLY FIRE"
    },
    {
        "id": "japanese_festival",
        "name": "Japanese Festival",
        "category": "Cultural",
        "description": "Scenic matsuri night festival backdrop with red lanterns and cherry blossoms.",
        "use_cases": "Kimono or Yukata outfits, night festival settings, colorful lanterns.",
        "visual_treatment": "Lantern red-orange glow reflections, cherry blossom overlays, night atmosphere.",
        "thumbnail": "style_japanese_festival.jpg",
        "bg_gradient": ((12, 10, 25), (60, 30, 50)),
        "face_tint": (1.05, 1.0, 1.02),
        "brightness": 0.98,
        "contrast": 1.08,
        "saturation": 1.15,
        "special_effect": None,
        "overlay": "sakura",
        "frame": None,
        "overlay_text": "まつり (MATSURI NIGHT)",
        "overlay_subtext": "UNDER LANTERN RAYS"
    },

    # ==========================================
    # ARTISTIC CATEGORY (9 Presets)
    # ==========================================
    {
        "id": "watercolor_painting",
        "name": "Watercolor Painting",
        "category": "Artistic",
        "description": "Beautiful fluid watercolor textures, canvas paper textures, and soft color bleeds.",
        "use_cases": "Artistic couple portraits, soft whimsical wall prints.",
        "visual_treatment": "Watercolor pigment texture, paper canvas background, soft outline bleed, vibrant wash.",
        "thumbnail": "style_watercolor_painting.jpg",
        "bg_gradient": ((245, 245, 240), (220, 235, 245)),
        "face_tint": (1.05, 1.02, 1.02),
        "brightness": 1.08,
        "contrast": 0.9,
        "saturation": 1.2,
        "special_effect": "watercolor",
        "overlay": None,
        "frame": None,
        "overlay_text": None,
        "overlay_subtext": None
    },
    {
        "id": "oil_painting",
        "name": "Oil Painting",
        "category": "Artistic",
        "description": "Classic fine-art canvas with visible thick brush strokes and oil varnish shine.",
        "use_cases": "Sophisticated portraits, museum-like artwork representations.",
        "visual_treatment": "Impasto oil texture overlay, high contrast, warm classical lighting, rich canvas paint.",
        "thumbnail": "style_oil_painting.jpg",
        "bg_gradient": ((35, 25, 20), (105, 80, 60)),
        "face_tint": (1.06, 1.0, 0.92),
        "brightness": 0.96,
        "contrast": 1.15,
        "saturation": 1.1,
        "special_effect": "oil",
        "overlay": "vignette",
        "frame": None,
        "overlay_text": "FINE ART STUDIO",
        "overlay_subtext": "OIL ON CANVAS"
    },
    {
        "id": "pencil_sketch",
        "name": "Sketch Art (Charcoal)",
        "category": "Artistic",
        "description": "Hand-drawn pencil sketch look with crosshatch shading and fine graphite lines.",
        "use_cases": "Minimalist monochrome art, sketchbooks, classic art prints.",
        "visual_treatment": "Monochrome sketch texture, crosshatch shading overlay, graphite outlines.",
        "thumbnail": "style_sketch.jpg",
        "bg_gradient": ((240, 240, 240), (210, 210, 210)),
        "face_tint": (0.9, 0.9, 0.9),
        "brightness": 1.0,
        "contrast": 1.3,
        "saturation": 0.0,
        "special_effect": "sketch",
        "overlay": None,
        "frame": None,
        "overlay_text": None,
        "overlay_subtext": None
    },
    {
        "id": "renaissance_art",
        "name": "Renaissance Art",
        "category": "Artistic",
        "description": "Classical oil paint style with dramatic chiaroscuro lighting and vintage cracked canvas.",
        "use_cases": "Dramatic poses, vintage dresses, classical fine art styling.",
        "visual_treatment": "Chiaroscuro high-contrast shadows, cracked paint textures, rich brown-gold wash.",
        "thumbnail": "style_renaissance_art.jpg",
        "bg_gradient": ((20, 15, 12), (65, 50, 35)),
        "face_tint": (1.08, 0.98, 0.88),
        "brightness": 0.88,
        "contrast": 1.25,
        "saturation": 0.95,
        "special_effect": "oil",
        "overlay": "vignette",
        "frame": "gold_foil",
        "overlay_text": "RENAISSANCE STUDY",
        "overlay_subtext": "CLASSICAL PORTRAITURE"
    },
    {
        "id": "pop_art",
        "name": "Pop Art",
        "category": "Artistic",
        "description": "Bold 1960s comic art style with Ben-Day dot patterns and bright solid coloring.",
        "use_cases": "Retro comic style, vibrant color lovers, playful couple photos.",
        "visual_treatment": "Ben-Day dot screen overlay, bold black outlines, ultra-vibrant primary colors.",
        "thumbnail": "style_pop_art.jpg",
        "bg_gradient": ((245, 0, 100), (0, 200, 255)),
        "face_tint": (1.1, 1.1, 1.1),
        "brightness": 1.1,
        "contrast": 1.4,
        "saturation": 1.5,
        "special_effect": "pop_art",
        "overlay": "grid",
        "frame": None,
        "overlay_text": "P O P !  A R T",
        "overlay_subtext": "LOVE EXPLOSION"
    },
    {
        "id": "abstract_love",
        "name": "Abstract Love",
        "category": "Artistic",
        "description": "Modern abstract art with floating colorful brush-strokes, shapes, and textures.",
        "use_cases": "Contemporary art pieces, creative profile designs.",
        "visual_treatment": "Geometric overlays, random colorful paint splatters, high artistic blending.",
        "thumbnail": "style_abstract_love.jpg",
        "bg_gradient": ((20, 20, 30), (120, 80, 160)),
        "face_tint": (1.05, 1.05, 1.05),
        "brightness": 1.05,
        "contrast": 1.1,
        "saturation": 1.35,
        "special_effect": None,
        "overlay": "sparkles",
        "frame": None,
        "overlay_text": "ABSTRACT UNION",
        "overlay_subtext": "LOVE CONCEPTS"
    },
    {
        "id": "impressionist",
        "name": "Impressionist Painting",
        "category": "Artistic",
        "description": "Dabbed Monet-style color strokes capturing fleeting outdoor light and movements.",
        "use_cases": "Garden dates, lake-side picnics, outdoor sunlight portraits.",
        "visual_treatment": "Impressionist canvas dabs, high color vibrance, soft-dappled lighting.",
        "thumbnail": "style_impressionist.jpg",
        "bg_gradient": ((100, 120, 160), (220, 200, 150)),
        "face_tint": (1.06, 1.04, 0.96),
        "brightness": 1.06,
        "contrast": 0.95,
        "saturation": 1.25,
        "special_effect": "oil",
        "overlay": "sunlight",
        "frame": None,
        "overlay_text": "IMPRESSION D'AMOUR",
        "overlay_subtext": "STUDIO MONET"
    },
    {
        "id": "digital_illustration",
        "name": "Digital Illustration",
        "category": "Artistic",
        "description": "Modern flat vector digital art style with clean lines and soft gradients.",
        "use_cases": "Modern avatars, graphic design representations, cartoon couple style.",
        "visual_treatment": "Vector-like smooth shading, clean minimalist shapes, bright flat highlights.",
        "thumbnail": "style_digital_illustration.jpg",
        "bg_gradient": ((200, 230, 245), (255, 220, 230)),
        "face_tint": (1.04, 1.04, 1.04),
        "brightness": 1.08,
        "contrast": 0.95,
        "saturation": 1.1,
        "special_effect": "posterize",
        "overlay": None,
        "frame": None,
        "overlay_text": "VECTOR HEART",
        "overlay_subtext": "FLAT DESIGN ILLUSTRATION"
    },
    {
        "id": "couple_portrait",
        "name": "Couple Portrait",
        "category": "Artistic",
        "description": "Classic clean studio photography portrait look with deep vignettes.",
        "use_cases": "Studio portraits, official announcements, elegant profile shots.",
        "visual_treatment": "Soft studio lights, neutral background, deep soft vignette, crisp skin textures.",
        "thumbnail": "style_portrait.jpg",
        "bg_gradient": ((30, 30, 30), (70, 70, 70)),
        "face_tint": (1.0, 1.0, 1.0),
        "brightness": 1.0,
        "contrast": 1.0,
        "saturation": 1.0,
        "special_effect": None,
        "overlay": "vignette",
        "frame": None,
        "overlay_text": None,
        "overlay_subtext": None
    }
]

# Quick lookup tables
PRESETS_BY_ID = {preset["id"]: preset for preset in STYLE_PRESETS}
PRESETS_BY_NAME = {preset["name"]: preset for preset in STYLE_PRESETS}
CATEGORIZED_PRESETS = {cat: [p for p in STYLE_PRESETS if p["category"] == cat] for cat in CATEGORIES}
